# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler for two-dimensional normal random numbers using R
#' @description A Gibbs sampler for two-dimensional normal random numbers using R
#' @param N the number of samples
#' @param mu1 the mean of the first dimension
#' @param mu2 the mean of the second dimension
#' @param sigma1 the standard deviation of the first dimension
#' @param sigma2 the standard deviation of the second dimension
#' @param pho the correlation of two dimensions
#' @return a random sample of size \code{N}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(N=2000, mu1=0, mu2=0, sigma1=1, sigma2=1, pho=0.9)
#' par(mfrow=c(1,3));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' plot(rnC)
#' }
#' @export
gibbsC <- function(N, mu1, mu2, sigma1, sigma2, pho) {
    .Call('_StatComp22064_gibbsC', N, mu1, mu2, sigma1, sigma2, pho)
}

#' @title Calculate the shortest path problem between cities using Rcpp.
#' @description The prediction model is described in https://www.math.pku.edu.cn/teachers/lidf/docs/Rbook/html/_Rbook/examples.html#examples-scicomp-citylink.
#' @param M the number of the city connected. It's a two-column matrix. The first number of each row is less than the second one.
#' @return a matrix of size \code{max(M)} whose elements are the minimum distances between cities.
#' @examples
#' \dontrun{
#' data(data)
#' distanceC <- shortestC(M)
#' }
#' @export
shortestC <- function(M) {
    .Call('_StatComp22064_shortestC', M)
}

